name: Disk debug stuff

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  disk-debug:
    runs-on: ubuntu-22.04
    steps:
    - name: Disk free at start
      run: df -h

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true    
    - name: Disk free at end
      run: df -h
  